### ISSUE TITLE
feat: option for non-generic cubit status

### ISSUE THREAD

**Issue by jenshor** [aumb/mason_templates#1]
**Description**

I'm not totally understanding why the generated (optional) status is a class with accepts a generic parameter. From the API, it's also not totally clear what the generic parameter is used for.

**Desired Solution**

As a developer, I'd like to have the option to configure whether I'd like to have the generic parameter.

**Alternatives Considered**

I'm currently deleting the generic parameter and go on from there.

**Comment by jenshor** [comment]
It looks like I've just created the very first issue for this brick 🎉👀. Let me stop here and thank you for your work. I use your brick constantly and would have implemented it myself if it didn't already exist. Great job - highly appreciate your efforts 👍🏻

Let me know if I misunderstood the usage of the generic parameter. I'm also happy to provide additional information if required. Just let me know 👍🏻

**Comment by aumb** [comment]
Hey @jenshor 👋 , thank you for opening this issue and for your extremely nice words!

You are absolutely correct, I use a generic `BaseStatus<T>`  class for all my cubits and define the generic `<T>` parameter as the cubit itself (ex: `BaseStatus<HomeCubit>` ), it totally went over my head that local classes do not actually need the generic parameter 👓 

I will remove the parameter all together probably by today or tomorrow thank you again, please don't hesitate to reach out if you have any other requests/concerns!

**Comment by jenshor** [comment]
Haha, that makes sense 😀. No hurries, but it's great to hear back from you so soon. Looking forward to the changes 👍

**Comment by aumb** [comment]
@jenshor should be fixed now!
